New contact notifications
publicv-org/publicv pull request #209
Opened 2021-09-01 11:39 UTC by kanchan-bluebash

Added notification icon for showing the new contacts with count. Also, new changes to open if user views the message.
Issue:- https://github.com/publicv-org/publicv/issues/159#issuecomment-908999982

https://user-images.githubusercontent.com/81285549/131665053-8f51dc93-f15d-4843-8646-5c6b54812eb6.mp4

2021-09-20 05:56 UTC, vishal-bluebash requested changes

2021-09-20 05:56 UTC, vishal-bluebash commented on app/controllers/application_controller.rb
> +  before_action :notifications
Use current_user condition here

2021-09-20 05:56 UTC, vishal-bluebash commented on app/controllers/application_controller.rb
> +    @new_contacts = @all_contacts.limit(4) if current_user.present?
We don't need limit here, you can pick first records as it is array

2021-09-21 07:44 UTC, duarme commented on config/locales/contacts.en.yml
> +    header: Hello, this is
Let's keep things simple, this should simply be "sender". We probably don't even need a label. Every time that something is obvious, we should omit that label.

2021-09-21 07:46 UTC, duarme reviewed
Cool feature! Only thing that I'd change is the "Hello this is". It's a nice idea but it's better to keep things as simple as possible. Let's say "Sender: " if needed.

2021-09-23 11:08 UTC, merged