[WIP] Admin Panel
publicv-org/publicv pull request #238
Opened 2021-11-16 10:40 UTC by ritik-bluebash

Issue:- #205 
Add admin panel.

2021-11-22 06:39 UTC, vishal-bluebash commented on app/controllers/admin/users_controller.rb
> +  # def destroy
Let's remove these

2021-11-22 06:50 UTC, vishal-bluebash commented on app/datatables/admin/flags_datatable.rb
> +      flags = flags.where(search_string.join(' or '), search: "%#{params[:search][:value]}%")
@ritik-bluebash Let's use to wrap user input in `sanitize_sql`, check elsewhere as well we will not use user input directly in SQL queries

https://api.rubyonrails.org/classes/ActiveRecord/Sanitization/ClassMethods.html#method-i-sanitize_sql

2021-11-22 06:51 UTC, vishal-bluebash commented on app/javascript/packs/admin.js
> +// import Turbolinks from 'turbolinks';
Let's remove these commented code

2021-11-22 06:52 UTC, vishal-bluebash commented on app/javascript/packs/application.js
> +window.DataTable = DataTable;
@ritik-bluebash Why do we need this here? as we are using datatables in admin layout only?

2021-11-22 06:53 UTC, vishal-bluebash commented on app/javascript/packs/application.js
>    console.log('Hello World from Webpacker');
Let's remove this

2021-11-22 06:54 UTC, vishal-bluebash commented on app/javascript/src/admin/scripts/search/index.js
> +  $('.search-toggle').on('click', e => {
use of jquery

2021-11-22 06:56 UTC, vishal-bluebash commented on app/views/admin/homes/show.html.erb
> +      <h6 class="lh-1">Welcome to PubliCV Admin Panel</h6>
We need ti setup translations for admin panel as well (Separate yml file)

2021-11-22 06:56 UTC, vishal-bluebash commented on app/views/admin/users/index.html.erb
> +      ajax: {
use of ajax, we need to use javascript

2021-11-22 06:57 UTC, vishal-bluebash commented on config/routes.rb
> +    resources :users, only: %i[index destroy]
get 'users/records', to: 'users#records'

This can be added in nested  of users

2021-11-22 06:57 UTC, vishal-bluebash requested changes
Reviewed and added comments

2021-12-28 07:06 UTC, vishal-bluebash commented
@ritik-bluebash Let's finish this PR and make it ready to merge

2021-12-28 10:46 UTC, ritik-bluebash commented on app/views/admin/users/index.html.erb
> +      ajax: {
Datatable initialization is based on jQuery

2021-12-28 10:50 UTC, ritik-bluebash commented on app/javascript/packs/application.js
> +window.DataTable = DataTable;
Updated to admin layout.

2021-12-30 08:11 UTC, vishal-bluebash approved these changes
Beta version is ready

2021-12-30 08:12 UTC, merged