Updated map message position to top
publicv-org/publicv pull request #277
Opened 2021-12-21 13:19 UTC by ritik-bluebash

Issue:- #255 
Added the message for user to use ctrl + zoom to be displayed over map

https://user-images.githubusercontent.com/80153678/146936361-a0c5e1a7-b877-4913-b02b-7c3765fb4cce.mp4

2021-12-22 10:34 UTC, vishal-bluebash commented
okay it is fine for now, in future we can improve. it

2021-12-22 10:34 UTC, vishal-bluebash approved these changes

2021-12-23 12:47 UTC, duarme requested changes

2021-12-23 12:47 UTC, duarme commented on app/javascript/src/javascripts/homepage_map.js
> +  if ($(window).width() > 767) {
Can we translate this into vanilla JS please, we need to drop jQuery, see #153

2021-12-27 06:45 UTC, vishal-bluebash approved these changes

2021-12-27 06:45 UTC, merged