Main project branch
publicv-org/publicv pull request #346
Opened 2022-01-24 12:54 UTC by ritik-bluebash

Project: #273 
Updating name from publiCV to youCV.

2022-02-03 18:31 UTC, ValerioVillani commented
I like It

2022-02-14 10:42 UTC, vishal-bluebash commented on app/concerns/default_url_options.rb
> +    ENV['EN_SERVER_HOST']
Better to have en.ucv.online or it.ucv.online as these domain represent our local

2022-02-14 10:49 UTC, vishal-bluebash commented on app/controllers/application_controller.rb
>    def root_domain_url
Is it still use? if yes logic looks hardcoded to EN not sure wyhy

2022-02-14 10:51 UTC, vishal-bluebash commented on app/models/cv.rb
> +  def salary_expectation
Better to use `?` when method returns boolean value true/false

2022-02-14 10:51 UTC, vishal-bluebash commented on app/models/cv.rb
> +  def notice_period_days
Better to use `?` when method returns boolean value true/false

2022-02-14 10:53 UTC, vishal-bluebash commented on app/views/layouts/shared/_header.html.erb
> +                  <option value="http://it.<%= ENV['EN_SERVER_HOST'] %>">Italian</option>
We need reusable helpers here

2022-02-14 10:54 UTC, vishal-bluebash requested changes
Feedback changes

2022-02-14 13:02 UTC, ritik-bluebash commented on app/controllers/application_controller.rb
>    def root_domain_url
EN_SERVER_HOST variable was set earlier. I used that only for setting URL's for different environment accordingly. So that the subdomain part and root domain url work accordingly on local, staging and production.
Now i have updated that to SERVER_URL.

2022-02-14 13:09 UTC, ritik-bluebash commented on app/models/cv.rb
> +  def salary_expectation
These are the key, values pairs of locale file.
https://github.com/publicv-org/publicv/pull/346/files#diff-0bdc16618c39e85b084c82c4b489a544b834d4b1501bba9ac96a4c6b3a2ca1b2

Used these pairs in view.
https://github.com/publicv-org/publicv/pull/346/files#diff-3a66806f5cc325223e92e7c2c179bb34da7cf2e18eb7bd16d36e40be34c1e8f8R29-R42
about and working_skills key is present in CV model and other keys are not present so used them as model methods.
if we have to change model methods then we will have to add question mark in yml file as well.

2022-02-14 13:18 UTC, ritik-bluebash commented on app/concerns/default_url_options.rb
> +    ENV['EN_SERVER_HOST']
Used an ENV variable named as SERVER_URL. Earlier we had two subdomains and mail was sent as per locale of app. Now, mail will be sent from single domain so no need of accessing host based on locale.

2022-02-14 13:19 UTC, ritik-bluebash commented on app/views/layouts/shared/_header.html.erb
> +                  <option value="http://it.<%= ENV['EN_SERVER_HOST'] %>">Italian</option>
Added helper method.!!

2022-02-14 13:35 UTC, vishal-bluebash commented on app/concerns/default_url_options.rb
> +    ENV['EN_SERVER_HOST']
this is for making URL's in email, so we need our urls like` en.ucv.online/signup` or `it.ucv.online/signup`

2022-02-17 07:08 UTC, vishal-bluebash approved these changes
@ritik-bluebash its ready, let's merge it to staging once we have a domain for staging on Cloudflare

2022-02-18 13:26 UTC, merged